Add ability to specify the API on the command line
ManageIQ/floe pull request #161
Opened 2024-03-22 22:43 UTC by kbrock

Our current workflows have the api endpoint url stored in `Context["Execution"]["_manageiq_api_url"]`.

Before
======

There is no way to set the api url in exe/floe

After
=====

```
./exe/floe --api http://localhost:3000/ workflow.asl "{}"
```

Comments
========

The `input` changes per workflow, so it makes sense to specify alongside the workflow in the ARGV.

The api endpoint url, on the other hand, is the same across all executions, so a single value make sense.

Discussion
==========

I had passed execution and input to context i.e.: `--execution '{_manageiq_api_url: "http://localhost:3000"}'`
While it felt nice and generic, it felt a little to brittle.

If there comes a point where this gem is used by multiple tools/companies, we can revisit
passing a generic execution parameter or rename `_manageiq_api_url` to `_api_url`.

This value is in every asl file. May make sense to rename to `ApiUrl` sooner rather than later

2024-03-27 17:37 UTC, Fryguy requested changes
> This name feels very manageiq specific.

That's because it is manageiq specific.  Anything manageiq specific should not be in this repository.

I think a more generic way to handle this is to take the execution state as a parameter instead, similar to how we take input or credentials.

2024-03-27 17:38 UTC, agrare commented
@kbrock the API passing is something specific to manageiq, could you just pass the execution as part of the context input that exists already?

2024-03-27 17:41 UTC, agrare commented
> context input that exists already?

Looks like we only accept `--input` on the command-line and build a context from that, I think if we also had a `--context` option you could do `floe --context '{"Execution": {"_manageiq_api_url": "http://localhost:3000"}} ...'

2024-03-27 18:03 UTC, kbrock commented
update:
- setting context (allows a partial context)

2024-03-27 22:45 UTC, kbrock commented
🍏 , but code climate says this is more complex. Which it is.
But ensuring all these extra fields work.

2024-03-27 23:07 UTC, Fryguy commented
I take code climate complexity with a grain of salt 😅

2024-03-28 13:21 UTC, agrare commented on exe/floe
> +  opt :context, "Context",                                      :type => :string
Suggest `JSON payload of the context`

2024-03-28 13:23 UTC, agrare commented on lib/floe/workflow/context.rb
> +        self["Task"] ||=         {}
```suggestion
        self["Execution"]          ||= {}
        self["Execution"]["Input"] ||= input
        self["State"]              ||= {}
        self["StateHistory"]       ||= []
        self["StateMachine"]       ||= {}
        self["Task"]               ||= {}
```

2024-03-28 13:48 UTC, agrare approved these changes

2024-03-28 13:48 UTC, merged

2024-03-28 13:49 UTC, agrare commented
@kbrock can you just update the title and description to match what we ended up doing?